### ISSUE TITLE
Menu Block Cache

### ISSUE THREAD

**Issue by kestraly** [magiccart/magento2-magicmenu#4]
Judging by the timings. The menu is not stored in block cache?

**Comment by magepow** [comment]
@kestraly Thanks for the report. I have added a block cache, please check again.

**Comment by kestraly** [comment]
So I found the best solution was to a specific megamenu cache.

This reduced the load time of the menu on a large store from 6 seconds to 0.6 seconds once cached.

Using this technique
https://www.optiweb.com/blog/magento-2-custom-cache-type/

I can put in a pull request with this. The only issue is the loss of the is_active feature. 

Adding the is_active feature through JQuery might be a better solution, so that you can have a fully cached menu that loads instantly and then jQuery highlights the active category by adding into the menu li data-categoryid="CATEGORY_ID"

example 
<li class="level0 category-item level-top" data-categoryid="10">Shop Online</li>

Then with jQuery something like that's on the page

$("magicmenu ul").find('[data-categoryid='10']').addClass('active');

**Comment by kestraly** [comment]
Closing - Added Pull Request
https://github.com/magiccart/magento2-magicmenu/pull/5
