### ISSUE TITLE
mobile menu broken on luma

### ISSUE THREAD

**Issue by ioweb-gr** [magiccart/magento2-magicmenu#7]
Right after installing the module on a fresh magento 2.4.1 with luma installation, the mobile menu navigation links stop working. 

Clicking the account tab won't switch the menu items

![image](https://user-images.githubusercontent.com/20220341/100653037-78adfa00-3350-11eb-84e5-9473ec939bfd.png)

**Comment by magiccart** [comment]
@ioweb-gr I have fixed it, please check again.

**Comment by ioweb-gr** [comment]
Yes fixed at dev-master :) great thank you very much
